In [3]:
import numpy as np
from numpy.linalg import norm, det, matrix_rank, inv, LinAlgError

# ==== CÂU 1 ====
A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])
C = np.array([
    [0, 3, 4],
    [1, 2, -1],
    [2, -1, 0]
])

# a)
A_plus_B = A + B
result_3A_minus_2B = 3 * A - 2 * B

# b)
dot_product = np.dot(A, B)
cos_theta = dot_product / (norm(A) * norm(B))
angle_degrees = np.degrees(np.arccos(cos_theta))

# c)
CTC = C.T @ C

# ==== CÂU 2 ====
M = np.array([
    [1, 2, 3, 0],
    [4, 5, 6, 1],
    [7, 8, 9, 2],
    [0, 1, 1, 0]
])
N = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11],
    [12, 13, 14, 15]
])

MN = M @ N
try:
    determinant_M = det(M)
except LinAlgError:
    determinant_M = "Không khả thi"
rank_N = matrix_rank(N)

# ==== CÂU 3 ====
P = np.array([
    [2, 1, 0, 1],
    [0, 3, 1, 4],
    [1, 0, 4, 2],
    [-1, 0, 1, 0]
])
b_vec = np.array([4, 7, 9, 5])

try:
    P_inv = inv(P)
    is_invertible = True
    x = P_inv @ b_vec
    check = P @ x
except LinAlgError:
    P_inv = None
    is_invertible = False
    x = None
    check = None

# ==== CÂU 4 ====
Q = np.array([
    [1, 3, 0],
    [4, -1, 0],
    [-2, 0, 2]
])
eigenvalues, eigenvectors = np.linalg.eig(Q)
normalized_vectors = np.array([v / norm(v) for v in eigenvectors.T]).T

# ==== CÂU 5 ====
R = np.array([
    [2, 0, 1],
    [1, -2, 3],
    [-1, 1, 4]
])
b5 = np.array([10, 8, 7])
x5 = np.linalg.solve(R, b5)

try:
    R_inv = np.linalg.inv(R)
    x5_via_inv = R_inv @ b5
    is_R_invertible = True
except LinAlgError:
    R_inv = None
    x5_via_inv = None
    is_R_invertible = False

frobenius_norm = norm(R, 'fro')

# ==== IN KẾT QUẢ ====
print("Câu 1:")
print("a) A + B =", A_plus_B)
print("   3A - 2B =", result_3A_minus_2B)
print("b) A · B =", round(dot_product, 3))
print("   Góc giữa A và B =", round(angle_degrees, 3), "độ")
print("c) C^T * C =\n", CTC)

print("\nCâu 2:")
print("a) M x N =\n", MN)
print("b) Định thức M =", round(determinant_M, 3) if isinstance(determinant_M, float) else determinant_M)
print("c) Hạng của N =", rank_N)

print("\nCâu 3:")
print("a) P khả nghịch:", is_invertible)
if is_invertible:
    print("   P⁻¹ =\n", np.round(P_inv, 3))
    print("b) Nghiệm x =", np.round(x, 3))
    print("c) Kiểm tra: P·x =", np.round(check, 3))
else:
    print("   Không khả nghịch")

print("\nCâu 4:")
print("a) Giá trị riêng =", np.round(eigenvalues, 3))
print("b) Vector riêng =\n", np.round(eigenvectors, 3))
print("c) Vector riêng chuẩn hóa =\n", np.round(normalized_vectors, 3))

print("\nCâu 5:")
print("a) Nghiệm Rx = b:", np.round(x5, 3))
print("b) R khả nghịch:", is_R_invertible)
if is_R_invertible:
    print("   R⁻¹ =\n", np.round(R_inv, 3))
    print("   Giải bằng R⁻¹·b =", np.round(x5_via_inv, 3))
else:
    print("   Không khả nghịch")

print("c) Chuẩn Frobenius của R =", round(frobenius_norm, 3))

Câu 1:
a) A + B = [3 3 1 5]
   3A - 2B = [  4 -11  13 -10]
b) A · B = -8
   Góc giữa A và B = 108.376 độ
c) C^T * C =
 [[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]

Câu 2:
a) M x N =
 [[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]
b) Định thức M = 0.0
c) Hạng của N = 2

Câu 3:
a) P khả nghịch: True
   P⁻¹ =
 [[ 0.4   -0.133  0.067 -0.133]
 [ 1.2   -0.067 -0.467  1.933]
 [ 0.4   -0.133  0.067  0.867]
 [-1.     0.333  0.333 -1.667]]
b) Nghiệm x = [ 0.6  9.8  5.6 -7. ]
c) Kiểm tra: P·x = [4. 7. 9. 5.]

Câu 4:
a) Giá trị riêng = [ 2.    -3.606  3.606]
b) Vector riêng =
 [[ 0.     0.536 -0.55 ]
 [ 0.    -0.822 -0.478]
 [ 1.     0.191  0.685]]
c) Vector riêng chuẩn hóa =
 [[ 0.     0.536 -0.55 ]
 [ 0.    -0.822 -0.478]
 [ 1.     0.191  0.685]]

Câu 5:
a) Nghiệm Rx = b: [3.826 1.435 2.348]
b) R khả nghịch: True
   R⁻¹ =
 [[ 0.478 -0.043 -0.087]
 [ 0.304 -0.391  0.217]
 [ 0.043  0.087  0.174]]
   Giải bằng R⁻¹·b = [3.826 1.435 2.348]
c) Chuẩn Frobenius của R = 6.083
